version: '3.8'

services:
  binance-mcp:
    build: .
    container_name: binance-mcp
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production